apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: class-operator-manager-role
rules:
- apiGroups:
  - nerc.mghpcc.org
  resources:
  - classes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nerc.mghpcc.org
  resources:
  - classes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nerc.mghpcc.org
  resources:
  - classes/finalizers
  verbs:
  - update
- apiGroups:
  - kubeflow.org
  resources:
  - notebooks
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - resourcequotas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  resourceNames:
  - edit
  verbs:
  - bind
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - user.openshift.io
  resources:
  - groups
  verbs:
  - get
  - list
  - watch
